# Generated by Django 5.2.13 on 2026-04-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_storeprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeprofile',
            name='city',
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='country_code',
            field=models.CharField(default='NG', max_length=5),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='industry',
            field=models.CharField(default='Retail', max_length=50),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='location',
            field=models.CharField(default='Lagos, Nigeria', max_length=100),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='region',
            field=models.CharField(default='tropical', max_length=20),
        ),
    ]
